### ISSUE TITLE
Modding

### ISSUE THREAD

**Issue by XxDarkus101Xx** [ProjectDonetsk/Defcon#4]
Hey man sorry to bother you again but what do we do after we build it? Do we like modify any files like unpacking then repacking them so the game can read them or something? Again so sorry for bothering you. Just want to edit weapon stats so the game can read them when I get done

**Comment by ZEROPOINTBRUH** [comment]
You can edit the files here
![devenv_JUU0qdOkvX](https://github.com/user-attachments/assets/b76b07b4-4026-466e-a506-0ffb8b379416)
![chrome_WseEgA5TTx](https://github.com/user-attachments/assets/0a1cddc6-8d3f-49ed-b90c-357f219c02fe)
